feat: update to latest proofs dependencies
filecoin-project/rust-filecoin-proofs-api pull request #52
Opened 2021-03-09 22:01 UTC by cryptonemo

fix: update proofs code to accomodate for the v6.x re-factors

2021-03-10 10:32 UTC, dignifiedquire requested changes
we should proxy the new `gpu2` flag through

2021-03-10 13:12 UTC, cryptonemo commented on Cargo.toml
> +gpu2 = ["filecoin-proofs-v1/gpu2", "filecoin-hashers/gpu2", "storage-proofs-core/gpu2", "fr32/gpu"]
I don't think bellperson has gpu2

2021-03-10 14:12 UTC, dignifiedquire commented on Cargo.toml
> +gpu2 = ["filecoin-proofs-v1/gpu2", "filecoin-hashers/gpu2", "storage-proofs-core/gpu2", "fr32/gpu"]
I know, but if because `gpu` is optional for all except for bellperson now

2021-03-10 15:39 UTC, cryptonemo commented on Cargo.toml
> +gpu2 = ["filecoin-proofs-v1/gpu2", "filecoin-hashers/gpu2", "storage-proofs-core/gpu2", "fr32/gpu"]
I'm not following.  Is there something specific missing that hasn't been pushed yet?

2021-03-11 11:18 UTC, dignifiedquire approved these changes
now it looks like I imagined :)

2021-03-11 12:43 UTC, merged